#!/bin/bash
echo "mkisofs -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o lp49-boot.cd  rootfs; cp lp49-boot.cd .."

mkisofs -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o lp49-boot.cd  rootfs; cp lp49-boot.cd ..
