% Copyright (C) 1995-2008 by Hiroshi Nakashima, Yasuki Saito and
%                            The Editorial Board of the IPSJ Journal
%
% ipsjpapers.cls 29-Dec-08 by Hiroshi Nakashima (ver 3.01)
% (revision history deleted)
% ipsjpapers.cls  1-Apr-96 by Hiroshi Nakashima (ver 2.00)

\ifx\pfmtname\undefined
\NeedsTeXFormat{LaTeX2e}
\else
\NeedsTeXFormat{pLaTeX2e}
\fi

\ProvidesClass{ipsjpapers}[2008/12/29 ver 3.01]
\input{ipsjpapers.sty}
\endinput
