#!/usr/bin/perl

print "/* Generated by: % ./mkerrlist.pl error.h > errlist.c  */\n";
while(<>) {
    if(m|extern char (E\w*)\[\]\;\s+/\* ([\w /]*)|) {  
	printf "char %s[]= \"%s\";\n",  $1, $2; 
    }
}

